// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CodeSendRequest struct {
	Email string `json:"email"`
}

type CodeSendResponse struct {
}

type CosObject struct {
	PartNumber int    `json:"part_number"`
	Etag       string `json:"etag"`
}

type FileChunkUploadCompleteRequest struct {
	Key        string      `json:"key"`
	UploadId   string      `json:"upload_id"`
	CosObjects []CosObject `json:"cos_objects"`
}

type FileChunkUploadCompleteResponse struct {
}

type FileChunkUploadRequest struct {
}

type FileChunkUploadResponse struct {
	Etag string `json:"etag"` // md5
}

type FileDeleteRequest struct {
	Identity string `json:"identity"`
}

type FileDeleteResponse struct {
}

type FileListRequest struct {
	Id   int64 `json:"id,optional" form:"id"`
	Page int   `json:"page,optional" form:"page"`
	Size int   `json:"size,optional" form:"size"`
}

type FileListResponse struct {
	List  []*UserFile `json:"list"`
	Count int64       `json:"count"`
}

type FileMoveRequest struct {
	Identity       string `json:"identity"`
	ParentIdentity string `json:"parent_identity"`
}

type FileMoveResponse struct {
}

type FilePreUploadRequest struct {
	Md5  string `json:"md5"`
	Name string `json:"name"`
	Ext  string `json:"ext"`
}

type FilePreUploadResponse struct {
	Identity string `json:"identity"`
	UploadId string `json:"upload_id"`
	Key      string `json:"key"`
}

type FileRenameRequest struct {
	Identity string `json:"identity"`
	Name     string `json:"name"`
}

type FileRenameResponse struct {
}

type FileUploadRequest struct {
	Hash string `json:"hash,optional"`
	Name string `json:"name,optional"`
	Ext  string `json:"ext,optional"`
	Size int64  `json:"size,optional"`
	Path string `json:"path,optional"`
}

type FileUploadResponse struct {
	Identity string `json:"identity"`
	Ext      string `json:"ext"`
	Name     string `json:"name"`
}

type FolderCreateRequest struct {
	Name     string `json:"name"`
	ParentId int64  `json:"parent_id"`
}

type FolderCreateResponse struct {
	Identity string `json:"identity"`
}

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
	Role         int    `json:"role"`
}

type RegisterRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Code     string `json:"code"`
}

type RegisterResponse struct {
}

type ResourceInfoRequest struct {
	Identity string `json:"identity,optional" form:"identity"`
}

type ResourceInfoResponse struct {
	RepositoryIdentity string `json:"repository_identity"`
	Name               string `json:"name"`
	Ext                string `json:"ext"`
	Size               int64  `json:"size"`
	Path               string `json:"path"`
}

type ResourceSaveRequest struct {
	RepositoryIdentity string `json:"repository_identity"`
	ParentId           int64  `json:"parent_id"`
	ShareIdentity      string `json:"share_identity,optional"`
}

type ResourceSaveResponse struct {
	Identity string `json:"identity"`
}

type ShareCreateRequest struct {
	RepositoryIdentity string `json:"repository_identity"`
	Expires            int    `json:"expires"`
}

type ShareCreateResponse struct {
	Identity string `json:"identity"`
}

type TokenRefreshRequest struct {
}

type TokenRefreshResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
	Role         int    `json:"role"`
}

type UserDetailRequest struct {
	Identity string `json:"identity"`
}

type UserDetailResponse struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type UserFile struct {
	Id                 int64  `json:"id"`
	Identity           string `json:"identity"`
	RepositoryIdentity string `json:"repository_identity"`
	Name               string `json:"name"`
	Ext                string `json:"ext"`
	Path               string `json:"path"`
	Size               int64  `json:"size"`
	UpdatedAt          string `json:"updated_at"`
}

type UserRepositoryRequest struct {
	ParentId           int64  `json:"parent_id"`
	RepositoryIdentity string `json:"repository_identity"`
	Ext                string `json:"ext"`
	Name               string `json:"name"`
}

type UserRepositoryResponse struct {
}
