// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"gopan/gopan/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/code/send",
				Handler: CodeSendHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/resource/info",
				Handler: ResourceInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/detail",
				Handler: UserDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: UserLoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/file/chunkupload",
					Handler: FileChunkUploadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/file/chunkupload/complete",
					Handler: FileChunkUploadCompleteHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/file/delete",
					Handler: FileDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/file/list",
					Handler: FileListHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/file/move",
					Handler: FileMoveHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/file/preupload",
					Handler: FilePreUploadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/file/rename",
					Handler: FileRenameHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/file/upload",
					Handler: FileUploadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/folder/create",
					Handler: FolderCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/resource/save",
					Handler: ResourceSaveHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/share/create",
					Handler: ShareCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/token/refresh",
					Handler: TokenRefreshHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/repository",
					Handler: UserRepositoryHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Admin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/admin/overview",
					Handler: AdminOverviewHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/users",
					Handler: AdminUserListHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/admin/user/status",
					Handler: AdminUserStatusUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/files",
					Handler: AdminFileListHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/admin/file",
					Handler: AdminFileDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/logs",
					Handler: AdminLogListHandler(serverCtx),
				},
			}...,
		),
	)
}
